spring:
  application:
    name: catalog-service

  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5433/bookshopdb_catalog

    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5


  config:
    import: "optional:configserver:"

  cloud:
    config:
      uri: http://localhost:8888

  sql:
    init:
      mode: always

server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5


bookshop:
  greeting: "Welcome to the bookshop catalog local!"

management:
  endpoints:
    web:
      exposure:
        include: refresh
